version: 2

updates:
- package-ecosystem: github-actions
  commit-message:
    prefix: chore
    include: scope
  directory: /
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
    timezone: Europe/Berlin
- package-ecosystem: npm
  commit-message:
    prefix: chore
    include: scope
  directory: /
  schedule:
    interval: weekly
    day: friday
    time: "18:00"
    timezone: Europe/Berlin
