#!/usr/bin/env bash
set -e

# Determine if an executable is in the PATH
if ! type -p node >/dev/null; then
   echo "Node not found on the system" >&2
   exit 1
fi

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

export GITHUB_TOKEN=$(gh auth token)

exec node ${SCRIPT_DIR}/index.js "$@"
