name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version:
          - 18
          - 20
          - 22

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: NPM install
        run: npm ci

      - name: Test Javascript code
        run: npm run test
